<div id="header">
  <div class="rmm" data-menu-style='minimal'>
    <ul>
      <li><a href="https://horizonplatform.io/">Home</a></li>
      <li><a href="https://horizonplatform.io/category/updates/">Updates</a></li>
      <li><a href="https://horizonplatform.io/wallets/">Wallets</a></li>
      <li><a href="http://nhzcrypto.org">Forum</a></li>
      <li><a href="https://faucet.horizonplatform.io">Faucet</a></li>
      <li><a href="https://explorer.horizonplatform.io">Explorer</a></li>
      <li><a href="https://horizonplatform.io/tutorial-videos/">Tutorials</a></li>
      <li><a href="https://horizonplatform.io/bounties/">Bounties</a></li>
    </ul>
  </div>
</div>
