<div class="container" style="padding-top: 50px;">
	<h1>Latest Blocks</h1>
	<div class="table-responsive">
		<table class="table table-striped">
			<thead>
				<tr>
					<th>Number</th>
					<th>Time</th>
					<th>Transactions</th>
					<th>Nrg used</th>
					<th>Miner</th>
				</tr>
			</thead>
			<tbody>
				<?php foreach($this->data['blocks'] as $block): ?>
					<tr>
						<td>
							<a href="?page=block&block=<?=$block['number']?>">
								<?=hexdec($block['number'])?>
							</a>
						</td>
						<td>
							<?=date('Y-m-d H:i:s',hexdec($block['timestamp']))?> UTC
						</td>
						<td><?=count($block['transactions'])?></td>
						<td><?=hexdec($block['gasUsed'])?></td>
						<td>
							<a href="?page=address&address=<?=$block['miner']?>">
								<?=$block['miner']?>
							</a>
						</td>
					</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	</div>
	<?php if((hexdec($block['number'])) > 9): ?>
    <a href="?blockStart=<?=hexdec($block['number'])-1?>">Previous</a>
	<?php endif; ?>

	<?php if((hexdec($block['number'])) < ($this->data['latest'])-10): ?>
    <a href="?blockStart=<?=hexdec($block['number'])+19?>">Next</a>
	<?php endif; ?>
	<p>
		<h1>Supply</h1>
		<?=number_format($this->data['supply'],0)?> SHIFT
		<h2>Network Hashrate</h2>
		<?=number_format($this->data['hashrate'],0)?> H/s || <?=number_format(($this->data['hashrate'])/1000,0)?> KH/s || <?=number_format(($this->data['hashrate'])/1000000,0)?> MH/s || <?=number_format(($this->data['hashrate'])/1000000000,3)?> GH/s
		<h2>Network Difficulty</h2>
		<?=number_format($this->data['difficulty'],0)?> H || <?=number_format(($this->data['difficulty'])/1000,0)?> KH || <?=number_format(($this->data['difficulty'])/1000000,0)?> MH || <?=number_format(($this->data['difficulty'])/1000000000,3)?> GH
	</p>
</div>