<section id="title" class="alizarin" style="padding:0px;">
  <div id="visible-phone-title" class="col-sm-12" style="text-align:center; margin-bottom:10px; padding:20px; padding-top:10px;">
    <div class="titleh1">
      <h2>Node Info</h2>
    </div>
  </div>
  <div id="visible-desktop-title" class="col-sm-12" style="text-align:center; margin-bottom:40px; padding:20px; padding-top:30px;">
    <div class="titleh1">
      <h1>Node Info</h1>
    </div>
    <p>You can check the state of your static node here.</p>
  </div>
  <div id="visible-tablet-title" class="col-sm-12" style="text-align:center; margin-bottom:80px; padding:20px; padding-top:40px;">
    <div class="titleh1">
      <h2>Node Info</h2>
    </div>
    <p>You can check the state of your static node here.</p>
  </div>
</section>
<div class="container">
  <div id="content" class="site-content" role="main">
    <article id="post-94" class="post-94 page type-page status-publish has-post-thumbnail hentry">
      <div class="entry-content">
        <div class="su-row">
          <div class="su-column su-column-size-3-4">
            <div class="su-column-inner su-clearfix" >
              <div  style="border:0px solid #000; text-align:right; width:100%; float:right; margin-left:10px;">
                <?=$this->element('nodecheckforms')?>
                <div id="checkNodeDiv">
                  <?=$this->element('nodestate',$this->data)?>
                </div>
              </div>
            </div>
          </div>
          <div class="su-column su-column-size-1-4">
            <div class="su-column-inner su-clearfix">
              <table>
                <tr>
                  <td><p class="dropcap"> This page shows all of the Horizon accounts that have been created so far. You can find more information about any account by clicking in the <strong>ACCOUNT</strong> column.</p>
                    <p>You can also sort this information by using the controls at the top.</p></td>
                </tr>
              </table>
            </div>
          </div>
        </div>
      </div>
    </article>
  </div>
</div>
<script type="text/javascript">
  $('#checkNodeForm').show();
  $('#checkNodesForm').hide();
</script> 
