Shift explorer API functions:<br />
<br />
<a class="address-link" href="api.php?page=supply">api.php?page=supply</a><br />
<a class="address-link" href="api.php?page=hashrate">api.php?page=hashrate</a><br />
<a class="address-link" href="api.php?page=blockcount">api.php?page=blockcount</a><br />
<a class="address-link" href="api.php?page=difficulty">api.php?page=difficulty</a><br />
api.php?searchFor=x<br />
api.php?page=address&address=x<br />
api.php?page=block&block=x<br />
api.php?page=transaction&tx=x<br />
